# Generated by Django 5.2.1 on 2025-06-09 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTaxSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('tax_name', models.CharField(choices=[('Supplier of Services (5%)', 'Supplier of Services (5%)'), ('Professional Fee (5%)', 'Professional Fee (5%)'), ('Rentals (5%)', 'Rentals (5%)'), ('Board of Directors (10%)', 'Board of Directors (10%)'), ('Consultant - Corporate (10%)', 'Consultant - Corporate (10%)')], max_length=100)),
                ('tax_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'year')},
            },
        ),
    ]
