# Generated by Django 5.2.1 on 2025-06-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_contract_of_service',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_freelancer',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_job_order',
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_type',
            field=models.CharField(blank=True, choices=[('freelancer', 'Freelancer'), ('jo', 'Job Order'), ('cos', 'Contract of Service')], max_length=20, null=True),
        ),
    ]
