# Generated by Django 5.2.1 on 2025-06-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_is_contract_of_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Freelancer', 'Freelancer'), ('JO', 'Job Order'), ('COS', 'Contract of Service')], max_length=20, null=True),
        ),
    ]
