# Generated by Django 5.2.1 on 2025-06-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='salary_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
